### ISSUE TITLE
java.nio.file.NoSuchFileException: ~/.signalfx/contacts/unreadcontacts.csv

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/wave-app#154]
With latest version, after sending a message or when opening the application, if there are messages sent:

```
01:24:16 3 [WebSocketConnection] [WSC] Thread[OkHttp https://textsecure-service.whispersystems.org/...,5,main] onMessage with type RESPONSE
01:24:16 3 [WebSocketConnection] listener for id -7885343703529223666 = org.whispersystems.signalservice.internal.websocket.WebSocketConnection$OutgoingRequest@338fb568
01:24:16 3 [SignalServiceMessageSender] sendMessageResponse = org.whispersystems.signalservice.internal.push.SendMessageResponse@26ea451 with needssync = false
01:24:16 3 [SignalServiceMessageSender] Result of sendMessage = org.whispersystems.signalservice.api.messages.SendMessageResult@5c254815
01:24:16 [DEBUG] [WaveLogger] [WM] sendSyncMessage done invoked
01:24:16 [DEBUG] [WaveLogger] sync requests are sent
Oct 31, 2021 1:24:17 AM com.gluonhq.attach.util.impl.DefaultServiceFactory createInstance
WARNING: No new instance for interface com.gluonhq.attach.keyboard.KeyboardService and class com.gluonhq.attach.keyboard.impl.DesktopKeyboardService
java.nio.file.NoSuchFileException: ~/.signalfx/contacts/unreadcontacts.csv
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:215)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:421)
        at java.base/java.nio.file.Files.readAllBytes(Files.java:3205)
        at java.base/java.nio.file.Files.readString(Files.java:3283)
        at java.base/java.nio.file.Files.readString(Files.java:3242)
        at com.gluonhq.chat@1.1.0-SNAPSHOT/com.gluonhq.chat.service.WaveService.readUnreadList(WaveService.java:310)
        at com.gluonhq.chat@1.1.0-SNAPSHOT/com.gluonhq.chat.service.WaveService$1.onChanged(WaveService.java:274)
        at javafx.base/com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
        at javafx.base/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
        at javafx.base/javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:239)
        at javafx.base/javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
        at javafx.base/javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
        at javafx.base/javafx.collections.ObservableListBase.endChange(ObservableListBase.java:211)
        at javafx.base/javafx.collections.ModifiableObservableListBase.add(ModifiableObservableListBase.java:162)
        at java.base/java.util.AbstractList.add(AbstractList.java:111)
        at com.gluonhq.chat@1.1.0-SNAPSHOT/com.gluonhq.chat.service.WaveService.readMessageForChannel(WaveService.java:167)
        at com.gluonhq.chat@1.1.0-SNAPSHOT/com.gluonhq.chat.service.WaveService.lambda$retrieveChannels$9(WaveService.java:124)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at com.gluonhq.chat@1.1.0-SNAPSHOT/com.gluonhq.chat.service.WaveService.retrieveChannels(WaveService.java:124)
        at com.gluonhq.chat@1.1.0-SNAPSHOT/com.gluonhq.chat.service.WaveService.getChannels(WaveService.java:114)
        at com.gluonhq.chat@1.1.0-SNAPSHOT/com.gluonhq.chat.views.ChannelPresenter.createChannelList(ChannelPresenter.java:76)
        at com.gluonhq.chat@1.1.0-SNAPSHOT/com.gluonhq.chat.views.ChannelPresenter.initialize(ChannelPresenter.java:34)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:77)
        at jdk.internal.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at javafx.base/com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:275)
        at javafx.fxml/com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:84)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2673)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2548)
        at javafx.fxml/javafx.fxml.FXMLLoader.load(FXMLLoader.java:2516)
        at afterburner.mfx@1.6.3/com.airhacks.afterburner.views.FXMLView.loadSynchronously(FXMLView.java:91)
        at afterburner.mfx@1.6.3/com.airhacks.afterburner.views.FXMLView.initializeFXMLLoader(FXMLView.java:100)
        at afterburner.mfx@1.6.3/com.airhacks.afterburner.views.FXMLView.getPresenter(FXMLView.java:179)
        at com.gluonhq.glisten.afterburner@2.1.0/com.gluonhq.charm.glisten.afterburner.AppView.lambda$registerView$0(AppView.java:133)
        at com.gluonhq.charm.glisten@6.1.0/com.gluonhq.impl.charm.glisten.util.CachedFactory.get(CachedFactory.java:32)
        at com.gluonhq.charm.glisten@6.1.0/com.gluonhq.charm.glisten.application.AppManager.retrieveView(AppManager.java:576)
        at com.gluonhq.chat@1.1.0-SNAPSHOT/com.gluonhq.chat.views.LandscapePresenter.loadLandscapeView(LandscapePresenter.java:50)
        at com.gluonhq.chat@1.1.0-SNAPSHOT/com.gluonhq.chat.views.HomePresenter.lambda$changeOrientation$2(HomePresenter.java:46)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at com.gluonhq.chat@1.1.0-SNAPSHOT/com.gluonhq.chat.views.HomePresenter.changeOrientation(HomePresenter.java:46)
        at com.gluonhq.chat@1.1.0-SNAPSHOT/com.gluonhq.chat.views.HomePresenter.lambda$new$0(HomePresenter.java:19)
        at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)

```

**Comment by johanvos** [comment]
should be fixed with #155
