### ISSUE TITLE
ConcurrentException on Linux

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/wave-app#67]
After pairing device, while retrieving contacts, several exceptions are thrown:

```
Exception in thread "JavaFX Application Thread" java.util.ConcurrentModificationException
        at java.base/java.util.AbstractList$RandomAccessSpliterator.checkAbstractListModCount(AbstractList.java:743)
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at com.gluonhq.chat@1.1.0-SNAPSHOT/com.gluonhq.chat.service.WaveService$2.lambda$invalidated$1(WaveService.java:113)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:290)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by jperedadnr** [comment]
Fixed with #74
